contact_links:
  - name: Join the Algo Community
    url: "https://forms.gle/8EpYfRgVmrDxXAio6"
    about: >
      If you would like to join the Algo community, please fill out the form to request an invitation.
      Provide details about your skills and motivation for joining. We will review your request and 
      send an invitation if approved.
