name: Update Contributors in README

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    name: Automate Contributors Update in README

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Contributors List in README
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        with:
          commit_message: "chore: update contributors list in README"
          committer_username: "ajay-dhangar"
          committer_email: "99037494+Ajay-Dhangar@users.noreply.github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
