name: Auto Comment on Issue
on:
  issues:
    types: [opened]
permissions:
  issues: write
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add Comment to Issue
        uses: actions/github-script@v6
        with:
          script: |
            const issueComment = `
              Thank you for creating this issue! 🎉 We'll look into it as soon as possible. 
              In the meantime, please make sure to provide all the necessary details and context. 
              If you have any questions or additional information, feel free to add them here. 
              Your contributions are highly appreciated! 😊

              You can also check our [CONTRIBUTING.md](https://github.com/ajay-dhangar/algo/blob/main/CONTRIBUTING.md) 
              for guidelines on contributing to this project.

              You may also visit our [DSA Roadmap](https://ajay-dhangar.github.io/algo/dsa-roadmap/) 
              for additional guidelines.

              **Resources for Guidance:** [Docusaurus Documentation](https://docusaurus.io/docs/docs-introduction), [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html), [Markdown Guide](https://www.markdownguide.org/), [MDX Documentation](https://mdxjs.com/docs/), [Mermaid Documentation](https://mermaid.js.org/)
            `;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: issueComment
            });
