name: "Handle Join Requests"

on:
  issues:
    types: [opened]

jobs:
  process_join_request:
    if: contains(github.event.issue.labels.*.name, 'join-request')
    runs-on: ubuntu-latest
    steps:
      - name: "Extract Form Data"
        id: extract_data
        run: |
          echo "Full Name: $(echo "${{ github.event.issue.body }}" | grep -A1 "Full Name" | tail -n1)" >> form_data.txt
          echo "Email: $(echo "${{ github.event.issue.body }}" | grep -A1 "Email" | tail -n1)" >> form_data.txt
          echo "GitHub Username: $(echo "${{ github.event.issue.body }}" | grep -A1 "GitHub Username" | tail -n1)" >> form_data.txt
          echo "Reason: $(echo "${{ github.event.issue.body }}" | grep -A1 "Why do you want to join" | tail -n1)" >> form_data.txt

      - name: "Send Form Data"
        if: always()
        env:
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: |
          echo "Sending form data to $EMAIL_RECIPIENT"
          curl --url "smtp://$SMTP_SERVER" --ssl-reqd \
            --mail-from "$EMAIL_SENDER" \
            --mail-rcpt "$EMAIL_RECIPIENT" \
            --upload-file form_data.txt \
            --user "$EMAIL_SENDER:$SMTP_PASSWORD"

      - name: "Close Join Request Issue"
        if: always()
        run: gh issue close ${{ github.event.issue.number }} --comment "Thank you for your request! The form has been submitted successfully."
